

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dccphub-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dccphub-network

  nginx:
    image: nginx:alpine
    container_name: dccphub-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dccphub-network

  db:
    image: postgres:16-alpine
    container_name: dccphub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dccphub-network

  redis:
    image: redis:alpine
    container_name: dccphub-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --databases 3
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dccphub-network

networks:
  dccphub-network:
    driver: bridge

volumes:
  dbdata:
  redis-data:
