
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dccp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dccp_network

  nginx:
    image: nginx:alpine
    container_name: dccp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - dccp_network

  db:
    image: postgres:16-alpine
    container_name: dccp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dccp_network

  redis:
    image: redis:alpine
    container_name: dccp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - dccp_network

networks:
  dccp_network:
    driver: bridge

volumes:
  dbdata:
  redisdata:
